print("Antecessor e Sucessor")
n =int(input("Digite valor: "))
print("Antecessor é {} é Seu Sucessor é {}".format((n - 1), (n + 1)))
print("="*50)
print("Mostrando Dobro, Raiz quadrada, triplo")
print("Seu dorbro é {}, \nSua raiz é {}, \nSeu triplo é {}".format((n*2), (n**(1/2)), (n*3)))
print("="*50)
nota = float(input("Infome primera nota:"))
nota2 = float(input("Informe Segunda nota:"))
soma = nota + nota2
print("A media do aluno é {}".format(soma/2))
print("="*50)
print("Converso de medidas ")
m = float(input("Digite uma distancia: "))
cm = m*100
mm = m*1000
print(" A medida de {}m corresponde {}cm e {}mm".format(m, cm , mm))
print("="*50)
print("Tabuada")
t = int(input("Informe um valor:"))
print("="*50)
print("{} X {} = {}".format(t, 1, t*1))
print("{} X {} = {}".format(t, 1, t*2))
print("{} X {} = {}".format(t, 1, t*3))
print("{} X {} = {}".format(t, 1, t*4))
print("{} X {} = {}".format(t, 1, t*5))
print("{} X {} = {}".format(t, 1, t*6))
print("{} X {} = {}".format(t, 1, t*7))
print("{} X {} = {}".format(t, 1, t*8))
print("{} X {} = {}".format(t, 1, t*9))
print("{} X {} = {}".format(t, 1, t*10))
print("="*50)
