print("Conversor de moedas")
v = float(input("Informe valor que deseja ser convertido: "))
print("Valor para converção {}, valor do dolar {}, Você pode comprar {:.2f} Dolar com {}".format(v, 4.26, v/4.26, v))
print("="*50)
l = float(input("largura:"))
al = float(input("Altura:"))
a = l + al
t = a/2
print("Sua parede é {} X {}, Sua area {}, Sera nesseçario para pintar {} de tintas".format(l, al, a ,t))
print("="*50)
valor = float(input("Digite um valor R$: "))
novo = valor - (valor*5/100)
print("Valor rm R$ {}, com desconto de 5% ficou {} ".format(valor, novo))
novo2 = valor + (valor*15/100)
print("Valor com aumento de 15%: {}".format(novo2))
print("="*50)
dias = float(input("Quantos dias:"))
km = float(input("Quantos KMs: "))
total = (dias * 60) + (km * 0.15)
print("Valor a ser pago é {}".format(total))
print("="*50)